[package]
name = "stringtape"
version = "0.1.0"
edition = "2021"
description = "A tape class for strings arrays compatible with Apache Arrow"
license = "Apache-2.0"

[lib]
path = "stringtape.rs"

[features]
default = []
